version: "3.9"
services:
  db:
    image: mysql:8.0.27
    container_name: bank_db
    env_file:
      BankSecurity.env
    ports:
      - '3306:3306'

  bank_security:
    build: .
    container_name: Bank_Server
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
    env_file:
      - BankSecurity.env